-- 프로젝트 최초 스키마: 메모 테이블
-- (당시에는 회원 개념이 없어 member_id가 없다. V3에서 추가된다)
create table memos (
    id         bigint generated by default as identity primary key,
    title      varchar(200)  not null,
    content    varchar(4000) not null,
    created_at timestamp(6)  not null
);
