-- 전체 스키마 베이스라인.
-- 과거 V1~V6로 나뉘어 있던 이력을 운영 배포 전(이력 보유 DB가 없는 마지막 시점)에 하나로 통합했다.
-- 이 파일이 적용된 DB가 생기는 순간부터는 이 파일을 수정할 수 없다 — 변경은 반드시 V2, V3...로 쌓는다.

-- 회원 ("사람"). 어떤 수단으로 로그인하는지는 auth_credentials가 담당한다.
create table members (
    id         bigint generated by default as identity primary key,
    email      varchar(100),                -- SNS 가입 시 동의하지 않으면 없을 수 있다
    nickname   varchar(20)  not null,
    created_at timestamp(6) not null,
    constraint uk_members_email unique (email)
);

-- 로그인 수단 ("문"). 회원 1 : 수단 N — 계정 연동의 기반.
-- LOCAL은 password(BCrypt 해시)만, SNS(KAKAO/GOOGLE)는 provider_id만 갖는다.
create table auth_credentials (
    id          bigint generated by default as identity primary key,
    member_id   bigint       not null,
    provider    varchar(20)  not null,
    provider_id varchar(100),
    password    varchar(100),
    created_at  timestamp(6) not null,
    constraint uk_auth_credentials_provider unique (provider, provider_id),
    constraint uk_auth_credentials_member_provider unique (member_id, provider),
    constraint fk_auth_credentials_member foreign key (member_id) references members (id)
);

-- refresh 토큰 (로그아웃 = 행 삭제, 만료 = expires_at 경과 후 새벽 배치가 정리)
create table refresh_tokens (
    id         bigint generated by default as identity primary key,
    token      varchar(100) not null,
    member_id  bigint       not null,
    expires_at timestamp(6) not null,
    constraint uk_refresh_tokens_token unique (token)
);

-- 메모. 도메인 경계 규칙(id 참조만)에 따라 members로의 FK는 의도적으로 걸지 않는다.
create table memos (
    id         bigint generated by default as identity primary key,
    title      varchar(200)  not null,
    content    varchar(4000) not null,
    member_id  bigint        not null,
    created_at timestamp(6)  not null
);

-- 태그 (전 회원이 공유, 이름 유일)
create table tags (
    id   bigint generated by default as identity primary key,
    name varchar(20) not null,
    constraint uk_tags_name unique (name)
);

-- 메모↔태그 다대다 중간 테이블
create table memo_tags (
    id      bigint generated by default as identity primary key,
    memo_id bigint not null,
    tag_id  bigint not null,
    constraint uk_memo_tags unique (memo_id, tag_id),
    constraint fk_memo_tags_memo foreign key (memo_id) references memos (id),
    constraint fk_memo_tags_tag foreign key (tag_id) references tags (id)
);
