-- 태그 도메인: 태그 + 메모-태그 다대다 중간 테이블
create table tags (
    id   bigint generated by default as identity primary key,
    name varchar(20) not null,
    constraint uk_tags_name unique (name)
);

create table memo_tags (
    id      bigint generated by default as identity primary key,
    memo_id bigint not null,
    tag_id  bigint not null,
    constraint uk_memo_tags unique (memo_id, tag_id),
    constraint fk_memo_tags_memo foreign key (memo_id) references memos (id),
    constraint fk_memo_tags_tag foreign key (tag_id) references tags (id)
);
