-- 회원 테이블 + 메모에 소유자(member_id) 추가
create table members (
    id         bigint generated by default as identity primary key,
    email      varchar(100) not null,
    password   varchar(100) not null,
    nickname   varchar(20)  not null,
    created_at timestamp(6) not null,
    constraint uk_members_email unique (email)
);

-- 도메인 경계 규칙(id 참조만)에 따라 members로의 FK는 의도적으로 걸지 않는다.
-- 운영 DB였다면 NOT NULL을 걸기 전에 기존 행을 채우는 단계가 필요하다:
--   alter table memos add column member_id bigint;
--   update memos set member_id = <기본 계정 id>;
--   alter table memos alter column member_id set not null;
-- 이 프로젝트는 도입 시점에 메모 데이터가 없어 바로 NOT NULL로 추가한다.
alter table memos
    add column member_id bigint not null;
