-- refresh 토큰 저장소 (로그아웃 = 행 삭제, 만료 = expires_at 경과)
create table refresh_tokens (
    id         bigint generated by default as identity primary key,
    token      varchar(100) not null,
    member_id  bigint       not null,
    expires_at timestamp(6) not null,
    constraint uk_refresh_tokens_token unique (token)
);
