-- 계정 연동 지원: 로그인 수단을 회원에서 분리한다 (회원 1 : 로그인 수단 N).
-- members는 "사람"만 남고, 어떤 문으로 들어오는지는 auth_credentials가 담당한다.
create table auth_credentials (
    id          bigint generated by default as identity primary key,
    member_id   bigint       not null,
    provider    varchar(20)  not null,
    provider_id varchar(100),
    password    varchar(100),
    created_at  timestamp(6) not null,
    constraint uk_auth_credentials_provider unique (provider, provider_id),
    constraint uk_auth_credentials_member_provider unique (member_id, provider),
    constraint fk_auth_credentials_member foreign key (member_id) references members (id)
);

-- 데이터 이전: 기존 회원의 로그인 수단(LOCAL이든 SNS든)을 새 테이블로 옮긴다.
-- LOCAL 행은 provider_id가, SNS 행은 password가 null인 상태 그대로 옮겨진다.
insert into auth_credentials (member_id, provider, provider_id, password, created_at)
    select id, provider, provider_id, password, created_at from members;

-- 이전이 끝난 뒤, members에서 로그인 수단 관련 컬럼을 제거한다.
-- (컬럼이 제약에 묶여 있으면 삭제가 거부되므로 제약을 먼저 내린다)
alter table members drop constraint uk_members_provider;
alter table members drop column provider;
alter table members drop column provider_id;
alter table members drop column password;
